// geotech/lib/projects-data.ts
//
// REAL GEODRILL geotechnical / geoscience project records (2025–2026 portfolio).
// Each row corresponds to a delivered project: bilingual name, location and
// client. Per-project photography is not yet available, so each card uses a
// representative category photo from `public/images/final/projects/`.
//
// To add real per-project photos later: drop the image into
// `public/images/projects/<id>.jpg` and set the `image` field on that record.

export type ProjectCategory =
  | "geotechnical"
  | "geophysical"
  | "survey"
  | "testing"
  | "structural"
  | "slope"
  | "shoring";

export type ProjectFilter = ProjectCategory | "all";

export interface Project {
  id: string;
  category: ProjectCategory;
  nameEn: string;
  nameAr: string;
  location: string;
  client: string;
  image: string;
  alt: string;
}

// Base path for the real site photography.
const P = "/images/final/projects";

// Representative, on-disk photos per service category (cycled across cards so a
// category grid does not repeat a single image).
const CATEGORY_IMAGES: Record<ProjectCategory, string[]> = {
  geotechnical: [
    `${P}/01_groundworks/concrete_rebar_footing.jpg`,
    `${P}/01_groundworks/excavation_foundation_pits.jpg`,
    `${P}/01_groundworks/groundworks_desert_grading.jpg`,
    `${P}/new_towers_highrise/structural_foundation_footings_v2.jpg`,
    `${P}/02_structures_and_steel/steel_frame_erection_wide.jpg`,
  ],
  geophysical: [
    `${P}/03_mep/mep_underfloor_conduit_slab.jpg`,
    `${P}/new_towers_highrise/cable_reels_infrastructure_site.jpg`,
    `${P}/01_groundworks/infrastructure_trench_layout.jpg`,
  ],
  survey: [
    `${P}/new_landscaping/landscape_garden_pathway_stones.jpg`,
    `${P}/01_groundworks/excavation_trench_wall.jpg`,
    `${P}/new_landscaping/landscape_pool_palm_walkway.jpg`,
  ],
  testing: [
    `${P}/03_mep/mep_basement_plant_room.jpg`,
    `${P}/new_mep_variety/mep_water_pump_ksb_blue.jpg`,
    `${P}/04_finishing/finishing_lobby_reception.jpg`,
  ],
  structural: [
    `${P}/02_structures_and_steel/steel_frame_closeup_sky.jpg`,
    `${P}/04_finishing/finishing_glass_office_partition.jpg`,
    `${P}/new_steel_variety/steel_interior_columns_wide.jpg`,
  ],
  slope: [
    `${P}/01_groundworks/excavation_deep_trench.jpg`,
    `${P}/new_misc_industrial/steel_frame_silo_tank_structure.jpg`,
    `${P}/02_structures_and_steel/steel_roof_truss_angle.jpg`,
  ],
  shoring: [
    `${P}/01_groundworks/excavation_deep_trench.jpg`,
    `${P}/01_groundworks/concrete_column_reinforcement.jpg`,
    `${P}/new_towers_highrise/cable_reels_infrastructure_site.jpg`,
  ],
};

function imageFor(category: ProjectCategory, index: number): string {
  const images = CATEGORY_IMAGES[category];
  return images[index % images.length];
}

export const projectBases: Record<ProjectCategory, string> = {
  geotechnical: `${P}/01_groundworks`,
  geophysical: `${P}/03_mep`,
  survey: `${P}/new_landscaping`,
  testing: `${P}/03_mep`,
  structural: `${P}/02_structures_and_steel`,
  slope: `${P}/01_groundworks`,
  shoring: `${P}/01_groundworks`,
};
// Each raw row: [category, nameEn, nameAr, location, client].
type RawRow = [ProjectCategory, string, string, string, string];

const rawRows: RawRow[] = [
  // ── Geotechnical ─────────────────────────────────────────────────────
  ["geotechnical",
    "Al Yamama Residential Tower – Al Olya Street, Riyadh",
    "الدراسة الجيوتقنية لبرج اليمامة للأجنحة الفندقية – العليا – الرياض",
    "Riyadh",
    "Four Direction Contracting Company"],
  ["geotechnical",
    "Al Munajem Main Warehouses – Riyadh",
    "الدراسة الجيوتقنية لمشروع مستودعات المنجم المركزية بالرياض",
    "Riyadh",
    "Abdullah Ali Al Munajem Sons"],
  ["geotechnical",
    "Park View (6 Commercial Towers) – King Abdulaziz Road",
    "الدراسة الجيوتقنية لمشروع بارك فيو (أبراج تجارية) طريق الملك عبد العزيز – الرياض",
    "Riyadh",
    "Yunineco Contracting"],
  ["geotechnical",
    "Schools Complex – Dhrat Laban, Riyadh",
    "الدراسة الجيوتقنية لمشروع مجمع تعليمي بظهرة لبن",
    "Riyadh",
    "Zas Trading & Contracting"],
  ["geophysical",
    "Geophysical Study – Awfa Commercial Towers, Hettien",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات لمشروع مجمعات أوفى التجارية بحي حطين",
    "Riyadh",
    "Awfa Investment"],
  ["geotechnical",
    "QC Testing – Boran Square, Olya Street, Riyadh",
    "اختبارات العناصر الخرسانية مجمع بوران سكوير العليا",
    "Riyadh",
    "Abdul Ilah Al Muhanna"],
  ["geotechnical",
    "Commercial & Residential Buildings – Al Rimal District, Riyadh",
    "الدراسة الجيوتقنية لمجمع سكني تجاري بحي الرمال – الرياض",
    "Riyadh",
    "Alfa Architects Development & Real Estate Investment"],
  ["geotechnical",
    "Forest Land Monitoring System (120 Towers) – Asir, Al-Baha, Najran & Makkah",
    "الدراسة الجيوتقنية لمشروع تصميم وإنشاء منظومة مراقبة أراضي الغابات – المرحلة الأولى والثانية (120 برج) بمناطق عسير والباحة ونجران ومكة",
    "Asir – Al-Baha",
    "Sayad Telecommunications & IT"],
  ["survey",
    "Topographic Survey – Malfa Living, Al-Arad District",
    "الرفع المساحي لمجمع مالفا بحي العارض",
    "Riyadh",
    "Mod Plus Partners"],
["geophysical",
    "Geophysical Study – Al Shbiely Tower, Al Muhamdia & Al Nakheel",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع أبراج الشبيلي بحي المحمدية والنخيل",
    "Riyadh",
    "Abdulrahman Abdullah Hammad Al Shbeili"],
  ["geophysical",
    "GPR Scanning – Al Nasr Club, Riyadh",
    "المسح الراداري لمشروع نادي النصر",
    "Riyadh",
    "MAC"],
  ["geotechnical",
    "Geotechnical & Topographic Survey – Lazord Housing, NHC – Khobar",
    "الدراسة الجيوتقنية والمساحية لمشروع إسكان لازورد التابع للشركة الوطنية للإسكان – الخبر – المنطقة الشرقية",
    "Eastern Region",
    "Bina Engineering Consultancy"],
  ["survey",
    "3D Laser Scanning – GOSI Building, Riyadh",
    "الرفع المساحي المعماري والإنشائي والتصوير ثلاثي الأبعاد لمشروع مبنى التأمينات الاجتماعية بالرياض",
    "Riyadh",
    "MAC"],
  ["geotechnical",
    "Commercial Buildings – Fakhria District, Riyadh",
    "الدراسة الجيوتقنية لمجمع تجاري بحي الفاخرية – الرياض",
    "Riyadh",
    "Summertown Real Estate Development"],
  ["geotechnical",
    "Hotel Building – Al Madina Al Munawarah",
    "الدراسة الجيوتقنية لمشروع مبنى فندقي – المدينة المنورة",
    "Madinah",
    "Qataf Investment & Real Estate Development"],
  ["slope",
    "Rock Slope Stability – Nubco Asir Logistics Pharmaceutical Warehouse, Khamis Mushait",
    "دراسة ثبات المنحدرات والإشراف على تنفيذ تثبيت الواجهة الصخرية لمشروع مستودعات شركة نوبكو بعسير",
    "Asir",
    "JASARA Program Management"],
  ["geotechnical",
    "Probing & Grouting – Malqa Al Andalus Commercial Project",
    "أعمال التخريم والحقن أسفل أماكن التكهفات والنطاقات الضعيفة ومعالجتها لمشروع ملقا الأندلس – الرياض",
    "Riyadh",
    "Saudi Construction Company"],
  ["geotechnical",
    "Geotechnical Investigation – Malqa Al Andalus Commercial Project",
    "الدراسة الجيوتقنية لمشروع ملقا الأندلس (مشروع تجاري) بحي القيروان – الرياض",
    "Riyadh",
    "Saudi Construction Company"],
["geotechnical",
    "Geotechnical Investigation – Mama Sauce Factory, Riyadh & Sudair",
    "الدراسة الجيوتقنية لمبنى مصنع صلصات ماما بالمدينة الصناعية بالرياض وسدير",
    "Sudair",
    "Mama Sauces Food Industries"],
  ["geotechnical",
    "Commercial Towers – King Salman Road, Riyadh",
    "برج سكني تجاري على القطع ١٨٦٧ إلى ١٨٧٠ من المخطط رقم ١٦٣٧/ك بحي الياسمين – الرياض",
    "Riyadh",
    "Mohammed Jameel Hammoud Al Turaiqi Real Estate Development"],
  ["geotechnical",
    "Al Rajhi Development Regional Headquarters – Abha City",
    "الدراسة الجيوتقنية لمشروع المبنى الإقليمي لشركة الراجحي للتطوير – مدينة أبها",
    "Abha",
    "Ahmad Al-Mousa Engineering Consultancy"],
  ["geotechnical",
    "Dr. Suliman Al Habib Palace & Villas – Hettien, Riyadh",
    "الدراسة الجيوتقنية لقصر وفلل الأولاد (مجمع حطين د. سليمان الحبيب)",
    "Riyadh",
    "Namara Investment"],
  ["geotechnical",
    "Yamama New Cement Plant Expansion – Kharj, Riyadh",
    "الدراسة الجيوتقنية لمشروع مصنع أسمنت اليمامة الجديد",
    "Kharj",
    "Sinoma Overseas Development"],
  ["survey",
    "Geotechnical & Topographic Survey – Dr. Suliman Al Habib Farm, Al Waseel",
    "الدراسة الجيوتقنية والرفع المساحي الطبوغرافي لمشروع مزرعة د. سليمان الحبيب بحي الوصيل – الرياض",
    "Riyadh",
    "Namara Investment"],
  ["testing",
    "Structural Assessment – Hotel Project, King Abdullah Road",
    "التقييم الإنشائي لمبنى فندقي على طريق الملك عبد الله – الرياض",
    "Riyadh",
    "Al Jazeera Medical"],
  ["geotechnical",
    "Geotechnical Investigation & Utilities Survey – Al-Diriyah Club",
    "الدراسة الجيوتقنية والمسح الراداري للخدمات – مشروع نادي الدرعية",
    "Riyadh",
    "Diriyah Club Company"],
  ["geotechnical",
    "Probing & Grouting – Al Shebily Tower Project",
    "أعمال التخريم والحقن أسفل أماكن التكهفات والنطاقات الضعيفة ومعالجتها لمشروع برج الشبيلي بحي المحمدية الرياض",
    "Riyadh",
    "Abdulrahman Abdullah Hammad Al Shbeili"],
  ["geotechnical",
    "Geotechnical Works – Pipe Lines Project, NWC – Riyadh",
    "الدراسة الجيوتقنية لمشروع ترحيل خطوط المياه المتعارضة مع مشروع وزارة النقل بطريق خريص القديم – الرياض",
    "Riyadh",
    "Environmental Systems Company"],
["testing",
    "Laboratory & Quality Control Testing – Dr. Suliman Al Habib, Hettien",
    "أعمال مراقبة الجودة الحقلية بمشاريع الدكتور سليمان الحبيب – حطين",
    "Riyadh",
    "Masah Contracting Company"],
  ["geotechnical",
    "Geotechnical Works – Commercial Tower, Ashbiliya, Riyadh",
    "الدراسة الجيوتقنية لمشروع مبنى سكني تجاري بحي اشبيليه – الرياض",
    "Riyadh",
    "Emar Al Tasheed Real Estate Development"],
  ["shoring",
    "Shoring & Slope Stability Design – Roshan Water Tanks, Sedra 1B",
    "تصميم أعمال السند لمشاريع خزانات روشن – خزانات مياه سدرة ١ب",
    "Riyadh",
    "Shibha Al Jazeera"],
  ["geotechnical",
    "Telalah Residences Phase 2 – Al Ared District, Riyadh",
    "الدراسة الجيوتقنية لمشروع تلالة السكني – مشارف الدولية",
    "Riyadh",
    "Mesharef International"],
  ["geotechnical",
    "Al Kredes Commercial Tower – Faisalia District",
    "الدراسة الجيوتقنية لمشروع مبنى تجاري (الكريديس) – بحي الفيصلية الرياض",
    "Riyadh",
    "Sawa'ed Architecture Engineering"],
  ["shoring",
    "Shoring System Design – Mixed-Use Residential & Commercial, Ashbiliyah",
    "تصميم أعمال السند مشروع مبانٍ تجارية وسكنية بحي اشبيلية",
    "Riyadh",
    "Emar Al Tasheed Real Estate Co"],
  ["geotechnical",
    "School Complex – Al Manar District, Riyadh",
    "الدراسة الجيوتقنية لمشروع مجمع مدارس الرؤية الجديدة العالمية – حي المنار – الرياض",
    "Riyadh",
    "Al Hajla Engineering Consultancy"],
  ["geotechnical",
    "Water Pipe Line – Riyadh",
    "الدراسة الجيوتقنية لمشروع عقد تغذية معسكر القيادة الموحدة لمجلس التعاون بحي النرجس – الرياض",
    "Riyadh",
    "Environmental Systems Company"],
  ["shoring",
    "Shoring System Design – Al Olya Towers",
    "تصميم أعمال السند لمشاريع أبراج العليا والمحمدية",
    "Riyadh",
    "Mubtakeron Real Estate Co"],
  ["geotechnical",
    "Geotechnical Works – Petrol Station, Various Regions of KSA",
    "الدراسة الجيوتقنية لمشاريع محطات بترول بمختلف مناطق المملكة",
    "Riyadh",
    "Al Drees Petroleum Services"],
  ["geophysical",
    "Geophysical Study – Al Sahafa Tower, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع مبنى برج سكني ومكتبي بحي الصحافة – الرياض",
    "Riyadh",
    "Saudi Construction Company"],
["structural",
    "Structural Assessment – Al Watania Central Warehouse, Al Haier",
    "التقييم الإنشائي لمبنى مستودعات الوطنية – الحائر – الرياض",
    "Riyadh",
    "Al Watania Industry"],
  ["geophysical",
    "Geophysical Study – Commercial/Office Tower, Al Ared, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع مبنى برج تجاري ومكتبي بحي العارض – الرياض",
    "Riyadh",
    "Laith Al Injaa Contracting"],
  ["geotechnical",
    "Yousef Al Rajhi Tower – Al Murooj, Riyadh",
    "الدراسة الجيوتقنية لمشروع برج إداري يوسف بن صالح الراجحي للاستثمار – بحي المروج – مدينة الرياض",
    "Riyadh",
    "Abdul Ilah Al Muhanna Engineering Consultancy"],
  ["geotechnical",
    "Diriyah FC Youth Facility – Dharat Laban, Riyadh",
    "الدراسة الجيوتقنية لمشروع نادي ظهرة لبن – الدرعية – المصيف الرياضي",
    "Riyadh",
    "Mahmoud Ahmed Shaban & Partner (MAC)"],
  ["geophysical",
    "GPR Scanning – Jubail Desalination Plant",
    "مسح راداري بمحطة تحلية مياه الجبيل – الكشف عن الخدمات تحت الأرض",
    "Jubail",
    "Mutlaq Al-Ghowairi Contracting Company"],
  ["geotechnical",
    "Probing & Grouting – Commercial/Office Tower, Al Ared",
    "أعمال التخريم والحقن أسفل أماكن التكهفات والنطاقات الضعيفة ومعالجتها لمشروع مبنى برج تجاري ومكتبي بحي العارض – الرياض",
    "Riyadh",
    "Laith Al Injaa Contracting"],
  ["geotechnical",
    "Commercial Towers – Al Murooj, Riyadh",
    "الدراسة الجيوتقنية لمشروع مبانٍ أبراج تجارية – مكتبية – سكنية بحي الياسمين – الرياض",
    "Riyadh",
    "Laith Al Injaa Contracting"],
  ["geophysical",
    "Geophysical Study – Noma Living Compound, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع مبنى سكني (نوما ليفينج ١) بحي السليمانية – الرياض",
    "Riyadh",
    "Faw Real Estate"],
  ["geophysical",
    "GPR & EM Scanning – Saudi Bio Factory, Sudair Industrial City",
    "مسح راداري للكشف عن التكهفات بمصنع سعودي بيو – سدير",
    "Sudair",
    "Exentec Co"],
  ["geotechnical",
    "Early Childhood Schools Project – Various Regions of KSA (15 Schools)",
    "الدراسة الجيوتقنية لمشروع مدارس الطفولة المبكرة بمختلف مناطق المملكة (١٥ مدرسة)",
    "Riyadh",
    "Ahmad Al-Mousa Engineering Consultancy"],
["geotechnical",
    "Al Hazem Commercial Buildings – Riyadh",
    "الدراسة الجيوتقنية لمشروع مجمع الحزم التجاري",
    "Riyadh",
    "Alworoud Real Estate Investment Company"],
  ["geotechnical",
    "Safwa Fad Commercial Towers – Al Ared, Riyadh",
    "الدراسة الجيوتقنية لمشروع برج سكني تجاري صندوق فاد العقاري بحي العارض – مدينة الرياض",
    "Riyadh",
    "Safwa Fad Real Estate"],
  ["shoring",
    "Shoring Design – Abraj Al Masar Tower, Al Aqeeq District",
    "تصميم أعمال السند مشروع برج أبراج المسار بحي العقيق",
    "Riyadh",
    "Abraj Al Masar Real Estate Co"],
  ["testing",
    "Testing of Concrete Structural Elements – Five Schools, Eastern Region",
    "اختبارات على العناصر الخرسانية بغرض التقييم الإنشائي لمبانٍ قائمة (عدد ٥ مدارس بالمنطقة الشرقية)",
    "Dammam",
    "Ahmad Al-Mousa Engineering Consultancy"],
  ["shoring",
    "Shoring System Design – Al-Madinah Water Transmission Line",
    "تصميم أعمال السند مشروع الخط الناقل للمياه بالمدينة المنورة",
    "Madinah",
    "Shibh Al Jazira Contracting Co"],
  ["geotechnical",
    "Al-Othaim Kunoz Mall & Towers – Khamis Mushait",
    "الدراسة الجيوتقنية لمشروع مول وأبراج كنوز العثيم – خميس مشيط",
    "Khamis Mushait",
    "Abdullah Al Othaim Investment Company"],
  ["geotechnical",
    "Commercial Buildings & Showrooms – Al Qirwan District, Riyadh",
    "الدراسة الجيوتقنية لمشروع إنشاء معارض تجارية وصالات حي القيروان – الرياض",
    "Riyadh",
    "Al Ajlan Holding"],
  ["geotechnical",
    "Residential Compounds – Al Mursalat, Al Sulimania & Al Narjes Districts",
    "الدراسة الجيوتقنية لمشروع كمباوند سكني بأحياء المرسلات – السليمانية – النرجس",
    "Riyadh",
    "Umq Real Estate"],
  ["shoring",
    "Foundation Pile Works – Warehouses & Workshops Project, Al Mather District",
    "تصميم وتنفيذ أعمال الخوازيق (الأساسات العميقة) لمجمع ورش ومستودعات أرض الجولف – المعذر",
    "Riyadh",
    "Nahr Al Fekr Contracting Co"],
  ["geotechnical",
    "Residential Compounds – Al Namuzajia & Um Al Hamam Al Gharbi Districts",
    "الدراسة الجيوتقنية لمشروع كمباوند سكني بأحياء النموذجية وأم الحمام الغربي بالرياض",
    "Riyadh",
    "Aseel Real Estate"],
  ["geotechnical",
    "Rafen Commercial Buildings – Al Nuzha District",
    "الدراسة الجيوتقنية لمشروع أرض النزهة – رافن – الرياض",
    "Riyadh",
    "Rafen Real Estate"],
  ["geophysical",
    "GPR Scanning & EM Survey – Jubail RO Plant",
    "مسح راداري لخطوط كهرباء بمحطة تحلية مياه الجبيل – محطة التناضح العكسي",
    "Jubail",
    "Mutlaq Al-Ghowairi Contracting Company"],
  ["geotechnical",
    "Fahd Al Owidah Commercial Tower – Al Aqeeq, Riyadh",
    "الدراسة الجيوتقنية لمشروع مبانٍ تجارية أرض وقف فهد العويضة – بحي العقيق – مدينة الرياض",
    "Riyadh",
    "Abdul Ilah Al Muhanna Engineering Consultancy"],
  ["geotechnical",
    "Palaces Project – Al Hada District, Riyadh",
    "الدراسة الجيوتقنية لمشروع قصور سكنية بحي الهدا – الرياض",
    "Riyadh",
    "Tasneem Housing"],
  ["geotechnical",
    "Geotechnical Works – Mosques in Riyadh",
    "الدراسة الجيوتقنية لمشروع مسجد الوالدة منيرة الجميح – بحي القيروان – مدينة الرياض",
    "Riyadh",
    "Abdul Ilah Al Muhanna Engineering Consultancy"],
  ["geotechnical",
    "Al Joud Commercial Tower – Al Rowdah, Riyadh",
    "الدراسة الجيوتقنية لمشروع برج سكني – بحي الروضة – الرياض",
    "Riyadh",
    "Al Waha Al Hamra Contracting"],
  ["geophysical",
    "GPR Scanning – Organic Solid Waste Treatment Plant Expansion, Makkah",
    "مسح راداري للخدمات لمشروع توسعة محطة معالجة النفايات الصلبة العضوية – مكة المكرمة",
    "Makkah",
    "Sets Company"],
  ["geophysical",
    "Geophysical Study – Signature Tower, Al Malqa, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع برج سكني سيغنيتشر – بحي الملقا الرياض",
    "Riyadh",
    "Mubtakeron Real Estate"],
  ["geotechnical",
    "Family Development Association Building – Al Ahsa",
    "الدراسة الجيوتقنية لمشروع إنشاء مبنى جمعية التنمية الأسرية بالمركز الحضري – مدينة الإحساء",
    "Al Ahsa",
    "Al Taraz Limited"],
];

// Build the exportable Project[] derived from the raw rows plus a stable id.
export const projects: Project[] = rawRows.map((row, index) => {
  const [category, nameEn, nameAr, location, client] = row;
  return {
    id: `project-${index + 1}`,
    category,
    nameEn,
    nameAr,
    location,
    client,
    image: imageFor(category, index),
    alt: nameEn || nameAr,
  };
});