// geotech/lib/projects-data.ts
//
// REAL GEODRILL geotechnical / geoscience project records (2025–2026 portfolio).
// Each row corresponds to a delivered project: bilingual name, location and
// client, plus a unique per-project photo from `public/images/geotech/projects/`.
// The photography is index-aligned with the project order (files named 01_…–68_…).

export type ProjectCategory =
  | "geotechnical"
  | "geophysical"
  | "survey"
  | "testing"
  | "structural"
  | "slope"
  | "shoring";

export type ProjectFilter = ProjectCategory | "all";

export interface Project {
  id: string;
  category: ProjectCategory;
  nameEn: string;
  nameAr: string;
  location: string;
  client: string;
  image: string;
  alt: string;
}

// Base path for the real per-project site photography (68 images).
const P = "/images/geotech/projects";

// One unique, already-processed image per project, index-aligned with
// `rawRows` below (order NN_… matches the project order 1–68). Naming follows
// NN_SERVICE_Project_Name.jpg as staged in `public/images/geotech/projects/`.
const PROJECT_IMAGES: string[] = [
  `${P}/01_Geo_Al_Yamama_Residential_tower_-_Al_Olya_street_-_Riy.jpg`,
  `${P}/02_Geo_Al_Munajem_main_warehouses_-_Riyadh.jpg`,
  `${P}/03_Geo_Park_view_6_commercial_towers_-_King_Abdulaziz_roa.jpg`,
  `${P}/04_Geo_Schools_complex_-_Dhrat_Laban_-_Riyadh.jpg`,
  `${P}/05_GYP_Geophysical_study_for_Awfa_Commercial_towers_-_Het.jpg`,
  `${P}/06_Geo_QC_testing_for_Boran_Squair_-_Olya_street_-_riyadh.jpg`,
  `${P}/07_Geo_Commercial_Resedintial_buildings_at_Al_Rimal_Distr.jpg`,
  `${P}/08_Geo_Geotechnical_Investigation_for_the_Design_and_Cons.jpg`,
  `${P}/09_TOPO_Topographic_survey_for_Malfa_Living_Al-Arad_Distri.jpg`,
  `${P}/10_GYP_Geophysical_study_for_Al_Shbiely_tower_-_Al_Muhamd.jpg`,
  `${P}/11_GYP_GPR_Scanning_for_Utilities_Detection_work_for_Site.jpg`,
  `${P}/12_GEO_TOPO_Geotechnical_and_topographic_survey_work_for_Lazor.jpg`,
  `${P}/13_TOPO_3D_laser_scanning_survey_for_GOSI_building_Project.jpg`,
  `${P}/14_GEO_Commercial_buildings_at_Fakhria_District_-_Riyadh.jpg`,
  `${P}/15_GEO_Hotel_Building_at_Al_Madina_Al_Munawarah.jpg`,
  `${P}/16_SS_ROCK_SLOPE_STABILITY_INVESTIGATION_SUPERVISION_WOR.jpg`,
  `${P}/17_GEO_Probing_Grouting_works_for_Malqa_Al_Andalus_commer.jpg`,
  `${P}/18_GEO_Geotechnical_investigation_works_for_Malqa_Al_Anda.jpg`,
  `${P}/19_GEO_Geotechnical_Investigation_works_for_Mama_Sauce_fa.jpg`,
  `${P}/20_GEO_Commercial_towers_at_King_Salman_Road.jpg`,
  `${P}/21_GEO_Geotechnical_works_for_Al_Rajhi_Development_Region.jpg`,
  `${P}/22_GEO_Geotechnical_works_for_DR_Suliman_Al_Habib_palace_.jpg`,
  `${P}/23_GEO_GEOTECHINAL_INVESTIGATION_WORKS_FOR_Yamama_New_Cem.jpg`,
  `${P}/24_TOPO_Geotechnical_and_topographic_survey_work_for_Dr_Su.jpg`,
  `${P}/25_QC_Structural_assessment_for_Hotel_project_at_King_Ab.jpg`,
  `${P}/26_GEIO_GEOTECHINAL_INVESTIGATION_Utilities_survey_WORKS_F.jpg`,
  `${P}/27_GEO_Probing_Grouting_works_for_Al_Shebily_tower_projec.jpg`,
  `${P}/28_GEO_Geotechnical_works_for_pipe_lines_project_with_NWC.jpg`,
  `${P}/29_QC_LABORATORY_AND_QUALITY_CONTROL_TESTING_FOR_DR_SULI.jpg`,
  `${P}/30_GEO_Geotechnical_works_for_commercial_tower_-_Ashbiliy.jpg`,
  `${P}/31_GEO_Design_Analysis_and_Specifications_for_Shoring_Sys.jpg`,
  `${P}/32_GEO_GEOTECHINAL_INVESTIGATION_WORKS_FOR_Telalah_Reside.jpg`,
  `${P}/33_GEO_Al_Kredes_Commercial_tower_-_Faisalia_District.jpg`,
  `${P}/34_SHO_Shoring_System_Design_Project_Mixed-Use_Residentia.jpg`,
  `${P}/35_GEO_Geotechnical_works_for_School_complex_-_Al_Manar_D.jpg`,
  `${P}/36_GEO_Geotechnical_works_for_Water_pipe_line_Riyadh.jpg`,
  `${P}/37_SHO_Design_of_a_Temporary_Excavation_Support_and_Shori.jpg`,
  `${P}/38_GEO_Geotechnical_works_for_Petrol_Station_-_around_ksa.jpg`,
  `${P}/39_GYP_Geophysical_study_for_Al_Sahafa_tower_-_Riyadh.jpg`,
  `${P}/40_SA_Structural_assessment_for_Al_Watania_central_wareh.jpg`,
  `${P}/41_GYP_Geophysical_study_for_Commercial_office_tower_-_Ri.jpg`,
  `${P}/42_GEO_Geotechnical_works_for_Yousef_Al_Rajhi_Tower_-_Al_.jpg`,
  `${P}/43_GEO_GEOTECHINAL_INVESTIGATION_WORKS_FOR_Diriyah_FC_You.jpg`,
  `${P}/44_GYP_GPR_Scanning_for_Underground_Utility_Detection_at_.jpg`,
  `${P}/45_GEO_Probing_Grouting_works_for_Commercial_office_tower.jpg`,
  `${P}/46_GEO_Geotechnical_works_for_Commercial_towers_-_Al_Muro.jpg`,
  `${P}/47_GPY_Geophysical_study_for_Noma_living_compound_-_Riyad.jpg`,
  `${P}/48_GYP_GPR_EM_Scanning_for_Underground_Utility_Detection_.jpg`,
  `${P}/49_GEO_Geotechnical_Investigation_for_the_Early_Childhood.jpg`,
  `${P}/50_GEO_GEOTECHINAL_INVESTIGATION_WORKS_FOR_-Al_Hazem_comm.jpg`,
  `${P}/51_GEO_Geotechnical_works_for_Safwa_Fad_Commercial_towers.jpg`,
  `${P}/52_Sho_shoring_design_for_the_Proposed_Commercial_Residen.jpg`,
  `${P}/53_GEO_Testing_of_Concrete_Structural_Elements_for_Struct.jpg`,
  `${P}/54_GEO_Shoring_System_Design_Al-Madinah_Water_Transmissio.jpg`,
  `${P}/55_GEO_GEOTECHINAL_INVESTIGATION_WORKS_FOR_Al-Othaim_Kuno.jpg`,
  `${P}/56_GEO_Geotechnical_works_for_Commercial_Buildings_Show_r.jpg`,
  `${P}/57_GEO_Geotechnical_works_for_Residintial_Compounds_-_Al_.jpg`,
  `${P}/58_pile_Execution_of_Foundation_Pile_for_warehouse_and_wor.jpg`,
  `${P}/59_GEO_Geotechnical_works_for_Residintial_Compounds_-_Al_.jpg`,
  `${P}/60_GEO_Geotechnical_works_for_Rafen_Commercial_Buildings_.jpg`,
  `${P}/61_GYP_GPR_Scanning_EM_survey_for_Underground_Utility_Det.jpg`,
  `${P}/62_GEO_Geotechnical_works_for_Fahd_Al_Owidah_Commercial_T.jpg`,
  `${P}/63_GEO_Geotechnical_works_forPalaces_projectr_at_Al_Hada_.jpg`,
  `${P}/64_GEO_Geotechnical_works_for_Mosques_in_Riyadh.jpg`,
  `${P}/65_GEO_Geotechnical_works_forAl_Joud_Commercial_tower_-_R.jpg`,
  `${P}/66_GYP_GPR_Scanning_for_Underground_Utility_Detection_for.jpg`,
  `${P}/67_GPY_Geophysical_study_for_Signature_tower_-_Riyadh.jpg`,
  `${P}/68_GEO_Geotechnical_works_for_Family_Development_Associat.jpg`,
];
// Each raw row: [category, nameEn, nameAr, location, client].
type RawRow = [ProjectCategory, string, string, string, string];

const rawRows: RawRow[] = [
  // ── Geotechnical ─────────────────────────────────────────────────────
  ["geotechnical",
    "Al Yamama Residential Tower – Al Olya Street, Riyadh",
    "الدراسة الجيوتقنية لبرج اليمامة للأجنحة الفندقية – العليا – الرياض",
    "Riyadh",
    "Four Direction Contracting Company"],
  ["geotechnical",
    "Al Munajem Main Warehouses – Riyadh",
    "الدراسة الجيوتقنية لمشروع مستودعات المنجم المركزية بالرياض",
    "Riyadh",
    "Abdullah Ali Al Munajem Sons"],
  ["geotechnical",
    "Park View (6 Commercial Towers) – King Abdulaziz Road",
    "الدراسة الجيوتقنية لمشروع بارك فيو (أبراج تجارية) طريق الملك عبد العزيز – الرياض",
    "Riyadh",
    "Yunineco Contracting"],
  ["geotechnical",
    "Schools Complex – Dhrat Laban, Riyadh",
    "الدراسة الجيوتقنية لمشروع مجمع تعليمي بظهرة لبن",
    "Riyadh",
    "Zas Trading & Contracting"],
  ["geophysical",
    "Geophysical Study – Awfa Commercial Towers, Hettien",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات لمشروع مجمعات أوفى التجارية بحي حطين",
    "Riyadh",
    "Awfa Investment"],
  ["geotechnical",
    "QC Testing – Boran Square, Olya Street, Riyadh",
    "اختبارات العناصر الخرسانية مجمع بوران سكوير العليا",
    "Riyadh",
    "Abdul Ilah Al Muhanna"],
  ["geotechnical",
    "Commercial & Residential Buildings – Al Rimal District, Riyadh",
    "الدراسة الجيوتقنية لمجمع سكني تجاري بحي الرمال – الرياض",
    "Riyadh",
    "Alfa Architects Development & Real Estate Investment"],
  ["geotechnical",
    "Forest Land Monitoring System (120 Towers) – Asir, Al-Baha, Najran & Makkah",
    "الدراسة الجيوتقنية لمشروع تصميم وإنشاء منظومة مراقبة أراضي الغابات – المرحلة الأولى والثانية (120 برج) بمناطق عسير والباحة ونجران ومكة",
    "Asir – Al-Baha",
    "Sayad Telecommunications & IT"],
  ["survey",
    "Topographic Survey – Malfa Living, Al-Arad District",
    "الرفع المساحي لمجمع مالفا بحي العارض",
    "Riyadh",
    "Mod Plus Partners"],
["geophysical",
    "Geophysical Study – Al Shbiely Tower, Al Muhamdia & Al Nakheel",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع أبراج الشبيلي بحي المحمدية والنخيل",
    "Riyadh",
    "Abdulrahman Abdullah Hammad Al Shbeili"],
  ["geophysical",
    "GPR Scanning – Al Nasr Club, Riyadh",
    "المسح الراداري لمشروع نادي النصر",
    "Riyadh",
    "MAC"],
  ["geotechnical",
    "Geotechnical & Topographic Survey – Lazord Housing, NHC – Khobar",
    "الدراسة الجيوتقنية والمساحية لمشروع إسكان لازورد التابع للشركة الوطنية للإسكان – الخبر – المنطقة الشرقية",
    "Eastern Region",
    "Bina Engineering Consultancy"],
  ["survey",
    "3D Laser Scanning – GOSI Building, Riyadh",
    "الرفع المساحي المعماري والإنشائي والتصوير ثلاثي الأبعاد لمشروع مبنى التأمينات الاجتماعية بالرياض",
    "Riyadh",
    "MAC"],
  ["geotechnical",
    "Commercial Buildings – Fakhria District, Riyadh",
    "الدراسة الجيوتقنية لمجمع تجاري بحي الفاخرية – الرياض",
    "Riyadh",
    "Summertown Real Estate Development"],
  ["geotechnical",
    "Hotel Building – Al Madina Al Munawarah",
    "الدراسة الجيوتقنية لمشروع مبنى فندقي – المدينة المنورة",
    "Madinah",
    "Qataf Investment & Real Estate Development"],
  ["slope",
    "Rock Slope Stability – Nubco Asir Logistics Pharmaceutical Warehouse, Khamis Mushait",
    "دراسة ثبات المنحدرات والإشراف على تنفيذ تثبيت الواجهة الصخرية لمشروع مستودعات شركة نوبكو بعسير",
    "Asir",
    "JASARA Program Management"],
  ["geotechnical",
    "Probing & Grouting – Malqa Al Andalus Commercial Project",
    "أعمال التخريم والحقن أسفل أماكن التكهفات والنطاقات الضعيفة ومعالجتها لمشروع ملقا الأندلس – الرياض",
    "Riyadh",
    "Saudi Construction Company"],
  ["geotechnical",
    "Geotechnical Investigation – Malqa Al Andalus Commercial Project",
    "الدراسة الجيوتقنية لمشروع ملقا الأندلس (مشروع تجاري) بحي القيروان – الرياض",
    "Riyadh",
    "Saudi Construction Company"],
["geotechnical",
    "Geotechnical Investigation – Mama Sauce Factory, Riyadh & Sudair",
    "الدراسة الجيوتقنية لمبنى مصنع صلصات ماما بالمدينة الصناعية بالرياض وسدير",
    "Sudair",
    "Mama Sauces Food Industries"],
  ["geotechnical",
    "Commercial Towers – King Salman Road, Riyadh",
    "برج سكني تجاري على القطع ١٨٦٧ إلى ١٨٧٠ من المخطط رقم ١٦٣٧/ك بحي الياسمين – الرياض",
    "Riyadh",
    "Mohammed Jameel Hammoud Al Turaiqi Real Estate Development"],
  ["geotechnical",
    "Al Rajhi Development Regional Headquarters – Abha City",
    "الدراسة الجيوتقنية لمشروع المبنى الإقليمي لشركة الراجحي للتطوير – مدينة أبها",
    "Abha",
    "Ahmad Al-Mousa Engineering Consultancy"],
  ["geotechnical",
    "Dr. Suliman Al Habib Palace & Villas – Hettien, Riyadh",
    "الدراسة الجيوتقنية لقصر وفلل الأولاد (مجمع حطين د. سليمان الحبيب)",
    "Riyadh",
    "Namara Investment"],
  ["geotechnical",
    "Yamama New Cement Plant Expansion – Kharj, Riyadh",
    "الدراسة الجيوتقنية لمشروع مصنع أسمنت اليمامة الجديد",
    "Kharj",
    "Sinoma Overseas Development"],
  ["survey",
    "Geotechnical & Topographic Survey – Dr. Suliman Al Habib Farm, Al Waseel",
    "الدراسة الجيوتقنية والرفع المساحي الطبوغرافي لمشروع مزرعة د. سليمان الحبيب بحي الوصيل – الرياض",
    "Riyadh",
    "Namara Investment"],
  ["testing",
    "Structural Assessment – Hotel Project, King Abdullah Road",
    "التقييم الإنشائي لمبنى فندقي على طريق الملك عبد الله – الرياض",
    "Riyadh",
    "Al Jazeera Medical"],
  ["geotechnical",
    "Geotechnical Investigation & Utilities Survey – Al-Diriyah Club",
    "الدراسة الجيوتقنية والمسح الراداري للخدمات – مشروع نادي الدرعية",
    "Riyadh",
    "Diriyah Club Company"],
  ["geotechnical",
    "Probing & Grouting – Al Shebily Tower Project",
    "أعمال التخريم والحقن أسفل أماكن التكهفات والنطاقات الضعيفة ومعالجتها لمشروع برج الشبيلي بحي المحمدية الرياض",
    "Riyadh",
    "Abdulrahman Abdullah Hammad Al Shbeili"],
  ["geotechnical",
    "Geotechnical Works – Pipe Lines Project, NWC – Riyadh",
    "الدراسة الجيوتقنية لمشروع ترحيل خطوط المياه المتعارضة مع مشروع وزارة النقل بطريق خريص القديم – الرياض",
    "Riyadh",
    "Environmental Systems Company"],
["testing",
    "Laboratory & Quality Control Testing – Dr. Suliman Al Habib, Hettien",
    "أعمال مراقبة الجودة الحقلية بمشاريع الدكتور سليمان الحبيب – حطين",
    "Riyadh",
    "Masah Contracting Company"],
  ["geotechnical",
    "Geotechnical Works – Commercial Tower, Ashbiliya, Riyadh",
    "الدراسة الجيوتقنية لمشروع مبنى سكني تجاري بحي اشبيليه – الرياض",
    "Riyadh",
    "Emar Al Tasheed Real Estate Development"],
  ["shoring",
    "Shoring & Slope Stability Design – Roshan Water Tanks, Sedra 1B",
    "تصميم أعمال السند لمشاريع خزانات روشن – خزانات مياه سدرة ١ب",
    "Riyadh",
    "Shibha Al Jazeera"],
  ["geotechnical",
    "Telalah Residences Phase 2 – Al Ared District, Riyadh",
    "الدراسة الجيوتقنية لمشروع تلالة السكني – مشارف الدولية",
    "Riyadh",
    "Mesharef International"],
  ["geotechnical",
    "Al Kredes Commercial Tower – Faisalia District",
    "الدراسة الجيوتقنية لمشروع مبنى تجاري (الكريديس) – بحي الفيصلية الرياض",
    "Riyadh",
    "Sawa'ed Architecture Engineering"],
  ["shoring",
    "Shoring System Design – Mixed-Use Residential & Commercial, Ashbiliyah",
    "تصميم أعمال السند مشروع مبانٍ تجارية وسكنية بحي اشبيلية",
    "Riyadh",
    "Emar Al Tasheed Real Estate Co"],
  ["geotechnical",
    "School Complex – Al Manar District, Riyadh",
    "الدراسة الجيوتقنية لمشروع مجمع مدارس الرؤية الجديدة العالمية – حي المنار – الرياض",
    "Riyadh",
    "Al Hajla Engineering Consultancy"],
  ["geotechnical",
    "Water Pipe Line – Riyadh",
    "الدراسة الجيوتقنية لمشروع عقد تغذية معسكر القيادة الموحدة لمجلس التعاون بحي النرجس – الرياض",
    "Riyadh",
    "Environmental Systems Company"],
  ["shoring",
    "Shoring System Design – Al Olya Towers",
    "تصميم أعمال السند لمشاريع أبراج العليا والمحمدية",
    "Riyadh",
    "Mubtakeron Real Estate Co"],
  ["geotechnical",
    "Geotechnical Works – Petrol Station, Various Regions of KSA",
    "الدراسة الجيوتقنية لمشاريع محطات بترول بمختلف مناطق المملكة",
    "Riyadh",
    "Al Drees Petroleum Services"],
  ["geophysical",
    "Geophysical Study – Al Sahafa Tower, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع مبنى برج سكني ومكتبي بحي الصحافة – الرياض",
    "Riyadh",
    "Saudi Construction Company"],
["structural",
    "Structural Assessment – Al Watania Central Warehouse, Al Haier",
    "التقييم الإنشائي لمبنى مستودعات الوطنية – الحائر – الرياض",
    "Riyadh",
    "Al Watania Industry"],
  ["geophysical",
    "Geophysical Study – Commercial/Office Tower, Al Ared, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع مبنى برج تجاري ومكتبي بحي العارض – الرياض",
    "Riyadh",
    "Laith Al Injaa Contracting"],
  ["geotechnical",
    "Yousef Al Rajhi Tower – Al Murooj, Riyadh",
    "الدراسة الجيوتقنية لمشروع برج إداري يوسف بن صالح الراجحي للاستثمار – بحي المروج – مدينة الرياض",
    "Riyadh",
    "Abdul Ilah Al Muhanna Engineering Consultancy"],
  ["geotechnical",
    "Diriyah FC Youth Facility – Dharat Laban, Riyadh",
    "الدراسة الجيوتقنية لمشروع نادي ظهرة لبن – الدرعية – المصيف الرياضي",
    "Riyadh",
    "Mahmoud Ahmed Shaban & Partner (MAC)"],
  ["geophysical",
    "GPR Scanning – Jubail Desalination Plant",
    "مسح راداري بمحطة تحلية مياه الجبيل – الكشف عن الخدمات تحت الأرض",
    "Jubail",
    "Mutlaq Al-Ghowairi Contracting Company"],
  ["geotechnical",
    "Probing & Grouting – Commercial/Office Tower, Al Ared",
    "أعمال التخريم والحقن أسفل أماكن التكهفات والنطاقات الضعيفة ومعالجتها لمشروع مبنى برج تجاري ومكتبي بحي العارض – الرياض",
    "Riyadh",
    "Laith Al Injaa Contracting"],
  ["geotechnical",
    "Commercial Towers – Al Murooj, Riyadh",
    "الدراسة الجيوتقنية لمشروع مبانٍ أبراج تجارية – مكتبية – سكنية بحي الياسمين – الرياض",
    "Riyadh",
    "Laith Al Injaa Contracting"],
  ["geophysical",
    "Geophysical Study – Noma Living Compound, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع مبنى سكني (نوما ليفينج ١) بحي السليمانية – الرياض",
    "Riyadh",
    "Faw Real Estate"],
  ["geophysical",
    "GPR & EM Scanning – Saudi Bio Factory, Sudair Industrial City",
    "مسح راداري للكشف عن التكهفات بمصنع سعودي بيو – سدير",
    "Sudair",
    "Exentec Co"],
  ["geotechnical",
    "Early Childhood Schools Project – Various Regions of KSA (15 Schools)",
    "الدراسة الجيوتقنية لمشروع مدارس الطفولة المبكرة بمختلف مناطق المملكة (١٥ مدرسة)",
    "Riyadh",
    "Ahmad Al-Mousa Engineering Consultancy"],
["geotechnical",
    "Al Hazem Commercial Buildings – Riyadh",
    "الدراسة الجيوتقنية لمشروع مجمع الحزم التجاري",
    "Riyadh",
    "Alworoud Real Estate Investment Company"],
  ["geotechnical",
    "Safwa Fad Commercial Towers – Al Ared, Riyadh",
    "الدراسة الجيوتقنية لمشروع برج سكني تجاري صندوق فاد العقاري بحي العارض – مدينة الرياض",
    "Riyadh",
    "Safwa Fad Real Estate"],
  ["shoring",
    "Shoring Design – Abraj Al Masar Tower, Al Aqeeq District",
    "تصميم أعمال السند مشروع برج أبراج المسار بحي العقيق",
    "Riyadh",
    "Abraj Al Masar Real Estate Co"],
  ["testing",
    "Testing of Concrete Structural Elements – Five Schools, Eastern Region",
    "اختبارات على العناصر الخرسانية بغرض التقييم الإنشائي لمبانٍ قائمة (عدد ٥ مدارس بالمنطقة الشرقية)",
    "Dammam",
    "Ahmad Al-Mousa Engineering Consultancy"],
  ["shoring",
    "Shoring System Design – Al-Madinah Water Transmission Line",
    "تصميم أعمال السند مشروع الخط الناقل للمياه بالمدينة المنورة",
    "Madinah",
    "Shibh Al Jazira Contracting Co"],
  ["geotechnical",
    "Al-Othaim Kunoz Mall & Towers – Khamis Mushait",
    "الدراسة الجيوتقنية لمشروع مول وأبراج كنوز العثيم – خميس مشيط",
    "Khamis Mushait",
    "Abdullah Al Othaim Investment Company"],
  ["geotechnical",
    "Commercial Buildings & Showrooms – Al Qirwan District, Riyadh",
    "الدراسة الجيوتقنية لمشروع إنشاء معارض تجارية وصالات حي القيروان – الرياض",
    "Riyadh",
    "Al Ajlan Holding"],
  ["geotechnical",
    "Residential Compounds – Al Mursalat, Al Sulimania & Al Narjes Districts",
    "الدراسة الجيوتقنية لمشروع كمباوند سكني بأحياء المرسلات – السليمانية – النرجس",
    "Riyadh",
    "Umq Real Estate"],
  ["shoring",
    "Foundation Pile Works – Warehouses & Workshops Project, Al Mather District",
    "تصميم وتنفيذ أعمال الخوازيق (الأساسات العميقة) لمجمع ورش ومستودعات أرض الجولف – المعذر",
    "Riyadh",
    "Nahr Al Fekr Contracting Co"],
  ["geotechnical",
    "Residential Compounds – Al Namuzajia & Um Al Hamam Al Gharbi Districts",
    "الدراسة الجيوتقنية لمشروع كمباوند سكني بأحياء النموذجية وأم الحمام الغربي بالرياض",
    "Riyadh",
    "Aseel Real Estate"],
  ["geotechnical",
    "Rafen Commercial Buildings – Al Nuzha District",
    "الدراسة الجيوتقنية لمشروع أرض النزهة – رافن – الرياض",
    "Riyadh",
    "Rafen Real Estate"],
  ["geophysical",
    "GPR Scanning & EM Survey – Jubail RO Plant",
    "مسح راداري لخطوط كهرباء بمحطة تحلية مياه الجبيل – محطة التناضح العكسي",
    "Jubail",
    "Mutlaq Al-Ghowairi Contracting Company"],
  ["geotechnical",
    "Fahd Al Owidah Commercial Tower – Al Aqeeq, Riyadh",
    "الدراسة الجيوتقنية لمشروع مبانٍ تجارية أرض وقف فهد العويضة – بحي العقيق – مدينة الرياض",
    "Riyadh",
    "Abdul Ilah Al Muhanna Engineering Consultancy"],
  ["geotechnical",
    "Palaces Project – Al Hada District, Riyadh",
    "الدراسة الجيوتقنية لمشروع قصور سكنية بحي الهدا – الرياض",
    "Riyadh",
    "Tasneem Housing"],
  ["geotechnical",
    "Geotechnical Works – Mosques in Riyadh",
    "الدراسة الجيوتقنية لمشروع مسجد الوالدة منيرة الجميح – بحي القيروان – مدينة الرياض",
    "Riyadh",
    "Abdul Ilah Al Muhanna Engineering Consultancy"],
  ["geotechnical",
    "Al Joud Commercial Tower – Al Rowdah, Riyadh",
    "الدراسة الجيوتقنية لمشروع برج سكني – بحي الروضة – الرياض",
    "Riyadh",
    "Al Waha Al Hamra Contracting"],
  ["geophysical",
    "GPR Scanning – Organic Solid Waste Treatment Plant Expansion, Makkah",
    "مسح راداري للخدمات لمشروع توسعة محطة معالجة النفايات الصلبة العضوية – مكة المكرمة",
    "Makkah",
    "Sets Company"],
  ["geophysical",
    "Geophysical Study – Signature Tower, Al Malqa, Riyadh",
    "الدراسة الجيوفيزيائية للكشف عن التكهفات بطريقة الماسو لمشروع برج سكني سيغنيتشر – بحي الملقا الرياض",
    "Riyadh",
    "Mubtakeron Real Estate"],
  ["geotechnical",
    "Family Development Association Building – Al Ahsa",
    "الدراسة الجيوتقنية لمشروع إنشاء مبنى جمعية التنمية الأسرية بالمركز الحضري – مدينة الإحساء",
    "Al Ahsa",
    "Al Taraz Limited"],
];

// Build the exportable Project[] derived from the raw rows plus a stable id.
export const projects: Project[] = rawRows.map((row, index) => {
  const [category, nameEn, nameAr, location, client] = row;
  return {
    id: `project-${index + 1}`,
    category,
    nameEn,
    nameAr,
    location,
    client,
    image: PROJECT_IMAGES[index],
    alt: nameEn || nameAr,
  };
});